# Generated by Django 2.0.7 on 2018-07-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=1)),
                ('specie', models.CharField(choices=[('P', 'Perro'), ('G', 'Gato')], max_length=1)),
                ('race', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('size', models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande')], max_length=1)),
                ('personality_1', models.TextField(blank=True, null=True)),
                ('personality_2', models.TextField(blank=True, null=True)),
                ('personality_joke', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
