# Generated by Django 2.0.7 on 2018-07-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180719_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='api.Adopter'),
        ),
    ]
