# Generated by Django 2.0.7 on 2018-07-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pet_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
