# Generated by Django 2.0.7 on 2018-07-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_association_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='specie',
            field=models.CharField(blank=True, choices=[('P', 'Perro'), ('G', 'Gato')], max_length=1, null=True),
        ),
    ]
