# Generated by Django 2.0.7 on 2018-07-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_answer_specie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('id',)},
        ),
    ]
