# Generated by Django 2.0.7 on 2018-07-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180720_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petimage',
            options={'ordering': ('id',)},
        ),
    ]
